version: "3.8"
services:

    service_worker:
        image: davidsoederberg/avanza-portfolio-tracker:worker
        container_name: worker
        networks:
            - network
        depends_on:
            - db
        env_file: 
            - .env
    service_verify:
        image: davidsoederberg/avanza-portfolio-tracker:verify
        container_name: verify
        networks:
            - network
        depends_on:
            - db
        env_file: 
            - .env
    db:
        container_name: mongo
        image: mongo
        networks:
            - network
        volumes:
            - mongodb_data_container:/data/db
networks:
    network:
volumes:
    mongodb_data_container:
