version: "3.8"
services:

    app:
        build: .
        networks:
            - network
        depends_on:
            - db
        environment:
            WAIT_HOSTS: mongo:27017
        env_file: 
            - .env
    db:
        container_name: mongo
        image: mongo
        networks:
            - network
networks:
    network: