name: Docker buildx
on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      -
        name: Run Buildx
        run: |
          docker buildx build --output "type=image,push=false" --platform linux/amd64,linux/arm/v7,linux/arm64 ./worker/
      -
        name: Docker Login
        if: success() && github.event_name != 'pull_request'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      -
        name: Build and Push to DockerHub
        if: success() && github.event_name != 'pull_request'
        run: |
          docker buildx build -t davidsoederberg/avanza-portfolio-tracker:worker --output "type=image,push=true" --platform linux/amd64,linux/arm/v7,linux/arm64 ./worker/
      -
        name: Clear
        if: always() && github.event_name != 'pull_request'
        run: |
          rm -f ${HOME}/runner/.docker/config.json
          rm -f ${HOME}/.docker/config.json
